config/routes.rb
Rails.application.routes.draw do
  resources :images do
    member do
      put '/add_to_top', action: :add_to_top
    end
    resources :votes
  end
  resources :categories
  mount Upmin::Engine => '/admin'
  devise_for :users
  resources :users
  get '/top', to: 'categories#show', as: :top, id: :top
  get '/oczekujace', to: 'categories#show', as: :oczekujace, id: :oczekujace
  get '/losowy_obrazek', to: 'images#random_image', as: :random_image
  root to: 'visitors#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :images
  validates_uniqueness_of :slug

  def to_param
    slug
  end

  def self.find_by_param(input)
    find_by_slug(input)
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  mount_uploader :picture, PictureUploader

  def votes_sum
    Vote.where(image_id: id).sum(:value)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?
  has_many :images

  def set_default_role
    self.role ||= :user
  end

  def can_vote_for_image?(image)
    Vote.where(user: self, image: image).empty?
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :get_images, only: :show

  expose(:categories) { Category.all }
  expose(
    :category,
    finder: :find_by_slug,
    finder_parameter: :id,
    attributes: :category_params
  )

  def create
    if category.save
      redirect_to category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def update
    if category.save
      redirect_to category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private

  def get_images
    category.images
  end

  def category_params
    params.require(:category).permit(:name, :slug, :default)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  def random_image
    @image = Image.order('RANDOM()').first
  end

  def create
    @image = Image.new(image_params)
    @image.picture = params[:file]
    @image.category = Category.find_by_default(true)
    @image.user = current_user

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_to_top
    if current_user.admin? || current_user.vip?
      set_image
      @image.update_attributes(category: Category.find_by_default(false))
      redirect_to top_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:title, :picture)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def vote_up
    if current_user.votes.empty?
      Vote.create(user: current_user, image_id: params[:image_id], value: 1)
      notice = 'Zagłosowałeś pomyslnie!'
    else
      notice = 'Glosowales juz na ten obrazek!'
    end
    redirect_to top_path, notice: notice
  end

  def vote_down
    if current_user.votes.empty?
      Vote.create(user: current_user, image_id: params[:image_id], value: -1)
      notice = 'Zagłosowałeś pomyslnie!'
    else
      notice = 'Glosowales juz na ten obrazek!'
    end
    redirect_to top_path, notice: notice
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/categories/_form.html.slim
= simple_form_for(category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :slug
    = f.input :default

  .form-actions
    = f.button :submit

app/views/categories/edit.html.slim
h1 Editing category

== render 'form'

= link_to 'Show', @category
'|
= link_to 'Back', categories_path

app/views/categories/index.html.slim
h1 Listing categories

table
  thead
    tr
      th Name
      th Slug
      th Default
      th
      th
      th

  tbody
    - categories.each do |category|
      tr
        td = category.name
        td = category.slug
        td = category.default
        td = link_to 'Show', category
        td = link_to 'Edit', edit_category_path(category)
        td = link_to 'Destroy', category, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Category', new_category_path

app/views/categories/new.html.slim
h1 New category

== render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.slim
h1
  = category.name

- category.images.each do |image|
  = "Glosy: #{image.votes_sum}"
  - if current_user.can_vote_for_image?(image)
    = link_to "+1", image_votes_path(image, '1'), method: :post, class: 'btn btn-success'
    = link_to "-1", image_votes_path(image, '-1'), method: :post, class: 'btn btn-danger'
  h2
    = image.title
  - if user_signed_in? && (current_user.admin? || current_user.vip?) && category.slug != 'top'
    = link_to 'Add to top', add_to_top_image_path(image), method: :put
  img src="#{image.picture}"
  br

app/views/images/_form.html.slim
= simple_form_for(@image) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :picture, as: :file

  .form-actions
    = f.button :submit

app/views/images/edit.html.slim
h1 Editing image

== render 'form'

= link_to 'Show', @image
'|
= link_to 'Back', images_path

app/views/images/index.html.slim
h1 Listing images

table
  thead
    tr
      th Title
      th Picture
      th User
      th Category
      th
      th
      th

  tbody
    - @images.each do |image|
      tr
        td = image.title
        td = image.picture
        td = image.user
        td = image.category
        td = link_to 'Show', image
        td = link_to 'Edit', edit_image_path(image)
        td = link_to 'Destroy', image, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Image', new_image_path

app/views/images/new.html.slim
h1 New image

== render 'form'

= link_to 'Back', images_path

app/views/images/random_image.html.slim
h2
  = @image.title
  img src="#{@image.picture}"

app/views/images/show.html.slim
p#notice = notice

p
  strong Title:
  = @image.title
p
  strong Picture:
  = @image.picture
p
  strong User:
  = @image.user
p
  strong Category:
  = @image.category

= link_to 'Edit', edit_image_path(@image)
'|
= link_to 'Back', images_path

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
li
  = link_to 'Oczekujące', oczekujace_path
li
  = link_to 'Top', top_path
li
  = link_to 'Losowy', random_image_path
- if user_signed_in?
  li
    = link_to 'Dodaj', new_image_path
  - if current_user.try(:admin?)
    li
      = link_to 'Admin', '/admin'
    li
      = link_to 'Users', users_path
  li
    = link_to 'Edytuj konto', edit_user_registration_path
  li
    = link_to 'Wyloguj', destroy_user_session_path, method: 'delete'
- else
  li
    = link_to 'Zaloguj się', new_user_session_path
  li
    = link_to 'Zarejestruj się', new_user_registration_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Kwejk'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Kwejk'}"
    == stylesheet_link_tag "application", :media => 'all'
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>